export const HomeTheme = {
  pageBg: '#f4f6f8',
  cardBg: '#ffffff',
  border: '#e0e4ea',
  textPrimary: '#2f3b46',
  textMuted: '#8a94a6',
  accent: '#c41e3a',
  lineTKL: '#7d2ca0',
  headerRule: '#c41e3a',
  refreshBg: '#ffffff',
  refreshBorder: '#d0d5dd',
  linkOutline: '#d0d5dd',
  linkSolid: '#c41e3a',
  error: '#b00020',
  headerBg: '#ffffff',
  headerBorder: '#e0e4ea',
  drawerOverlay: 'rgba(0, 0, 0, 0.4)',
  drawerActiveBg: '#fde8eb',
  drawerBg: '#ffffff',
} as const;
